//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempted_Quiz
    {
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> Course_UserTaskID { get; set; }
        public Nullable<int> QuizID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Obtainedmarks { get; set; }
        public Nullable<int> ResultStatus { get; set; }
        public Nullable<int> AttemptsDone { get; set; }
    
        public virtual Course_UserTask Course_UserTask { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
