//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Course_File = new HashSet<Course_File>();
            this.Course_UserTask = new HashSet<Course_UserTask>();
            this.Quizs = new HashSet<Quiz>();
            this.CourseGroupStudies = new HashSet<CourseGroupStudy>();
            this.GroupTasks_Details = new HashSet<GroupTasks_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsPublished { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> NoFile { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ResultAnnoucement { get; set; }
        public string TitleImage { get; set; }
        public Nullable<int> CreateCertificate { get; set; }
        public Nullable<int> IsScorm { get; set; }
        public string ScormCourseFile { get; set; }
        public string SignatureImage { get; set; }
        public string CertificateValidity { get; set; }
        public string Citation { get; set; }
        public string SignatureText { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_File> Course_File { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_UserTask> Course_UserTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quizs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseGroupStudy> CourseGroupStudies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTasks_Details> GroupTasks_Details { get; set; }
    }
}
