//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_UserTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_UserTask()
        {
            this.Attempted_Quiz = new HashSet<Attempted_Quiz>();
            this.Meetings = new HashSet<Meeting>();
            this.Quiz_Result = new HashSet<Quiz_Result>();
            this.UserTask_QuizResult = new HashSet<UserTask_QuizResult>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> User_TaskID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TotalMarks { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public Nullable<int> ResultStatus { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> IsResultUpdated { get; set; }
        public Nullable<int> ResultUpdatedBy { get; set; }
        public Nullable<int> IsLead { get; set; }
        public Nullable<int> CourseGroupStudyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attempted_Quiz> Attempted_Quiz { get; set; }
        public virtual Course Course { get; set; }
        public virtual User_Task User_Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Result> Quiz_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTask_QuizResult> UserTask_QuizResult { get; set; }
    }
}
