//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelegateFile
    {
        public int Id { get; set; }
        public Nullable<int> FileVersionId { get; set; }
        public Nullable<int> SharedWith { get; set; }
        public Nullable<int> SharedBy { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> IsOutside { get; set; }
        public string ShareableLink { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual FileVersion FileVersion { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
