//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionRequest
    {
        public int Id { get; set; }
        public Nullable<int> GroupTaskDetails_Id { get; set; }
        public Nullable<int> RequestedDays { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Displayed { get; set; }
        public Nullable<int> User_TaskId { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual GroupTasks_Details GroupTasks_Details { get; set; }
        public virtual User_Task User_Task { get; set; }
    }
}
