//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTasks_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupTasks_Details()
        {
            this.ExtensionRequests = new HashSet<ExtensionRequest>();
            this.GroupTask_Ticket = new HashSet<GroupTask_Ticket>();
            this.GroupTask_User = new HashSet<GroupTask_User>();
            this.GroupTaskComments = new HashSet<GroupTaskComment>();
            this.GroupTaskReminders = new HashSet<GroupTaskReminder>();
            this.User_Task = new HashSet<User_Task>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<double> CEU { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<int> GroupTaskId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Priority { get; set; }
        public string SlackChannel { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> TicketSortBy { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> RepeatTime { get; set; }
        public Nullable<int> RepeatDeadline { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtensionRequest> ExtensionRequests { get; set; }
        public virtual GroupTask GroupTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTask_Ticket> GroupTask_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTask_User> GroupTask_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTaskComment> GroupTaskComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTaskReminder> GroupTaskReminders { get; set; }
        public virtual User User { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Task> User_Task { get; set; }
    }
}
