//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTask_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupTask_User()
        {
            this.GroupTaskComments = new HashSet<GroupTaskComment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> LeadRole { get; set; }
        public Nullable<int> GroupTaskDetailsId { get; set; }
        public Nullable<System.DateTime> BeforeDDateReminder { get; set; }
        public Nullable<int> DailyReminder { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual GroupTasks_Details GroupTasks_Details { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTaskComment> GroupTaskComments { get; set; }
    }
}
