//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTaskComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupTaskComment()
        {
            this.GroupTaskComment1 = new HashSet<GroupTaskComment>();
        }
    
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> GroupTaskUserId { get; set; }
        public string Date { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string File { get; set; }
        public string FileName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GroupTaskDetailsId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> GTaskStartDate { get; set; }
        public Nullable<System.DateTime> GTaskEndDate { get; set; }
        public Nullable<int> IsDocMFile { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Division Division { get; set; }
        public virtual GroupTask_User GroupTask_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTaskComment> GroupTaskComment1 { get; set; }
        public virtual GroupTaskComment GroupTaskComment2 { get; set; }
        public virtual User User { get; set; }
        public virtual GroupTasks_Details GroupTasks_Details { get; set; }
        public virtual User User1 { get; set; }
    }
}
