//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.User_Meeting = new HashSet<User_Meeting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Course_UserTaskId { get; set; }
        public Nullable<int> UserTaskId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> HostId { get; set; }
        public string RoomName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public Nullable<int> IsCanceled { get; set; }
        public Nullable<int> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> MeetingType { get; set; }
    
        public virtual Course_UserTask Course_UserTask { get; set; }
        public virtual User User { get; set; }
        public virtual User_Task User_Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Meeting> User_Meeting { get; set; }
    }
}
