//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_File
    {
        public int Id { get; set; }
        public string File { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
