//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.GroupTask_Task = new HashSet<GroupTask_Task>();
            this.User_Task = new HashSet<User_Task>();
            this.TaskFiles = new HashSet<TaskFile>();
            this.TaskTags = new HashSet<TaskTag>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Name { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost_ { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<double> CEU { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string File { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> IsResultAnnounced { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTask_Task> GroupTask_Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Task> User_Task { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskFile> TaskFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTag> TaskTags { get; set; }
    }
}
