//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Task()
        {
            this.Course_UserTask = new HashSet<Course_UserTask>();
            this.ExtensionRequests = new HashSet<ExtensionRequest>();
            this.Meetings = new HashSet<Meeting>();
            this.Task_Ticket = new HashSet<Task_Ticket>();
            this.TaskComments = new HashSet<TaskComment>();
            this.User_Task1 = new HashSet<User_Task>();
            this.CourseGroupStudies = new HashSet<CourseGroupStudy>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> CEU { get; set; }
        public Nullable<int> Grad { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> CreatedID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string File { get; set; }
        public Nullable<int> RepeatTime { get; set; }
        public Nullable<int> RepeatDeadline { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> BeforeDDateReminder { get; set; }
        public Nullable<int> DailyReminder { get; set; }
        public Nullable<int> CanvasCourseId { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> TicketSortBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> TemplateCreatedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> GroupTaskDetailId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_UserTask> Course_UserTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtensionRequest> ExtensionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Ticket> Task_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Task> User_Task1 { get; set; }
        public virtual User_Task User_Task2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseGroupStudy> CourseGroupStudies { get; set; }
        public virtual GroupTasks_Details GroupTasks_Details { get; set; }
    }
}
